### ISSUE TITLE
Sentry: Error uploading sourcemap file - Error: connect EADDRNOTAVAIL 35.188.42.15:443 - Local 

### ISSUE THREAD

**Issue by igorescobar** [arabold/serverless-sentry-plugin#63]
Hi,

A few days from now we started to get this error on our pipelines:
```
Error ---------------------------------------------------
 
  Error: Sentry: Error uploading sourcemap file - Error: connect EADDRNOTAVAIL 35.188.42.15:443 - Local (172.17.0.2:0)
      at SentryPlugin.<anonymous> (/builds/services/node_modules/serverless-sentry/dist/index.js:603:31)
      at step (/builds/services/node_modules/serverless-sentry/dist/index.js:44:23)
      at Object.throw (/builds/new10/services/node_modules/serverless-sentry/dist/index.js:25:53)
      at rejected (/builds/services/node_modules/serverless-sentry/dist/index.js:17:65)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.19.3
     Framework Version:         2.72.3 (local)
     Plugin Version:            5.5.4
     SDK Version:               4.3.2
     Components Version:        3.18.2
```

This is what our dependencies look like at the moment:
```json
    "@sentry/integrations": "^7.2.0",
    "@sentry/node": "^7.2.0",
    "serverless-sentry-lib": "^2.5.0",
    "serverless-sentry": "^2.5.0",
```

We even tried to disable this functionality by adding the environment variable `SENTRY_SOURCEMAPS` or adding the custom config:
```yml
sentry:
    sourceMaps: false
```
But it runs regardless and ignores the flag. Do you have any idea what is happening and how to work around this?

**Comment by igorescobar** [comment]
Maybe is this related?
https://stackoverflow.com/questions/21859537/connect-eaddrnotavail-in-nodejs-under-high-load-how-to-faster-free-or-reuse-tc

**Comment by igorescobar** [comment]
Maybe we are being too aggressive here:
https://github.com/arabold/serverless-sentry-plugin/blob/master/src/index.ts#L476 and we are running out of TCP ports because of the large number of files being sent?

**Comment by igorescobar** [comment]
Yeah, I also noticed that after upgrading to there is no way to disable the source maps upload. the only way is rolling it back.

**Comment by arabold** [comment]
I'm literally on a plane right now but should have a quick fix in a bit.

**Comment by arabold** [comment]
No risk, no fun. Just published a fully untested 2.5.1 that (hopefully) fixes two problems:

- Fix [#63](https://github.com/arabold/serverless-sentry-lib/issues/63): Upload source maps serially to avoid running out of sockets.
- Correctly disable uploading source maps if the config setting is `false` or unset.

🤞

**Comment by igorescobar** [comment]
> Fix [#63](https://github.com/arabold/serverless-sentry-lib/issues/63): Upload source maps serially to avoid running out of sockets.

Maybe we should do this in batches here. instead of calling all of them in parallel creating batches of 50-100 requests might fix the issue. In our case it would take ages to submit all files I suppose.

**Comment by arabold** [comment]
The best would be to upload like 3 to 5 simultaneously for best performance. 50-100 parallel connections are a lot. But I currently lack the time and ability to test this properly, so I went for the quickest fix. It's slower but should work regardless of how large the project is and how many artifacts it has to upload.

**Comment by igorescobar** [comment]
> The best would be to upload like 3 to 5 simultaneously for best performance. 50-100 parallel connections are a lot. But I currently lack the time and ability to test this properly, so I went for the quickest fix. It's slower but should work regardless of how large the project is and how many artifacts it has to upload.

I would also create a property to configure it if necessary. It will be hard to come up with a config that will be nice for everyone so be conservative but also allow people to be more aggressive if they have the computing power to do so 👍

**Comment by arabold** [comment]
I have another update 2.5.2. Can you give it a try? It will upload 5 in parallel which should not impact your performance anymore. 10, 20, 50 really shouldn't make a noticeable difference, but feel free to adjust it and try it out if you notice something. I'm open to any changes. Again, this is fully untested 🙄

**Comment by arabold** [comment]
v2.5.2 fixes the peer dependency now

**Comment by igorescobar** [comment]
### Tests checklist
- [x] Source code is now honoring the `sourceMaps` default `false` and it deployed the application with no issues.
- [ ] `sourceMaps: true` (test in progress)

**Comment by arabold** [comment]
😞 How long did it take before my changes to serialize the upload?

**Comment by igorescobar** [comment]
7 minutes.  Almost 30 minutes now.

**Comment by igorescobar** [comment]
(I stopped the job at 45min)

**Comment by igorescobar** [comment]
Thanks! 🚀 
I'm testing it out and I will let you know.

**Comment by igorescobar** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/24032/175095985-d8a35cc5-038f-4f9b-ac8e-667d04ec7b8d.png">
😄

**Comment by igorescobar** [comment]
With that being said... we definitely need to add some retries and grace period into this logic. If you consider that you can have multiple builds running at the same time you don't want to fail the entire build because of this.

**Comment by igorescobar** [comment]
```js
import { PromisePool } from '@supercharge/promise-pool'

const errors = []

const { results } = await PromisePool
  .for(users)
  .handleError(async (error, user) => {
      // you must collect errors yourself
    if (error instanceof ValidationError) {
      return errors.push(error)
    }

    // Process error handling on specific errors
    if (error instanceof ThrottleError) {
      return await retryUser(user)
    }
  })
  .process(async data => {
    // the harder you work for something,
    // the greater you’ll feel when you achieve it
  })

await handleCollected(errors) // this may throw

return { results }
```

**Comment by igorescobar** [comment]
Just an update on my side. We found out a few other ways @sentry recommends for source map upload and we ended up using https://github.com/getsentry/sentry-webpack-plugin which also uploads the source maps to their service and it worked nicely for us. 👍
